<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class Handler extends ExceptionHandler
{
    /*** A list of the exception types that are not reported. ***/
    protected $dontReport = [
        //
    ];

    /*** A list of the inputs that are never flashed for validation exceptions. ***/
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];


    /*** Register the exception handling callbacks for the application. ***/
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }


    public function render($request, Throwable $e)
    {
        if ($e instanceof NotFoundHttpException){
            return redirect()->route('not_found');
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }

}
